branch-defaults:
  main:
    environment: PLT-env   
environment name
    group_suffix: null

global:
  application_name: PLT   
application name
  default_region: us-east-1
  platform: Node.js 22 running on 64bit Amazon Linux 2023
  profile: null
  sc: git