name: Deploy Node.js App to Elastic Beanstalk

on:
  push:
    branches:
      - main   # deploy only when code is merged into main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Build Frontend
      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      # 4. Copy Frontend Build into Backend
      - name: Copy Build to Backend
        run: |
          rm -rf backend/build
          cp -r frontend/build backend/build
          rm -rf frontend/build

      # 5. Install Backend Dependencies
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install --production

      # 6. Zip Backend for Elastic Beanstalk
      - name: Zip Backend
        run: |
          cd backend
          zip -r ../app.zip ./*

      # 7. Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 8. Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        run: |
          aws s3 cp app.zip s3://elasticbeanstalk-${{ secrets.AWS_REGION }}-$(aws sts get-caller-identity --query Account --output text)/app-${GITHUB_SHA}.zip

          aws elasticbeanstalk create-application-version \
            --application-name "${{ secrets.EB_APP_NAME }}" \
            --version-label "build-${GITHUB_SHA}" \
            --source-bundle S3Bucket="elasticbeanstalk-${{ secrets.AWS_REGION }}-$(aws sts get-caller-identity --query Account --output text)",S3Key="app-${GITHUB_SHA}.zip"

          aws elasticbeanstalk update-environment \
            --environment-name "${{ secrets.EB_ENV_NAME }}" \
            --version-label "build-${GITHUB_SHA}"